insert into address (id, postalCode, city, street, house) values (1, 4028, 'Debrecen', 'Kassai', 26);
insert into address (id, postalCode, city, street, house) values (2, 4032, 'Debrecen', 'Egyetem ter', 1);
insert into address (id, postalCode, city, street, house) values (3, 4032, 'Debrecen', 'Szikes', 16);
insert into address (id, postalCode, city, street, house) values (4, 4028, 'Debrecen', 'Kassai', 49);
insert into address (id, postalCode, city, street, house) values (5, 4028, 'Debrecen', 'Dessewffy', 11);
insert into address (id, postalCode, city, street, house) values (6, 4031, 'Debrecen', 'Bethlen', 50);
insert into address (id, postalCode, city, street, house) values (7, 4030, 'Debrecen', 'Homok', 47);

insert into user (id, username, hashedPass, role, name) values (1, 'username1', 'itshashed', 'admin', 'Nagy Lajos');
insert into user (id, username, hashedPass, role, name) values (2, 'username2', 'itshashed', 'user', 'Kis Ferenc');
insert into user (id, username, hashedPass, role, name) values (3, 'username3', 'itshashed', 'user', 'Balogh Roland');
insert into user (id, username, hashedPass, role, name) values (4, 'username4', 'itshashed', 'user', 'John Doe');
insert into user (id, username, hashedPass, role, name) values (5, 'username5', 'itshashed', 'user', 'Petrik Alexandra');
insert into user (id, username, hashedPass, role, name) values (6, 'username6', 'itshashed', 'user', 'Novak Ilona');
insert into user (id, username, hashedPass, role, name) values (7, 'username7', 'itshashed', 'user', 'Teszt Elek');
insert into user (id, username, hashedPass, role, name) values (8, 'username8', 'itshashed', 'user', 'Csicsek Szabolcs');
insert into user (id, username, hashedPass, role, name) values (9, 'username9', 'itshashed', 'user', 'Csernyik Patrik');
insert into user (id, username, hashedPass, role, name) values (10, 'username10', 'itshashed', 'user', 'Tisza Norbert');
insert into user (id, username, hashedPass, role, name) values (11, 'username11', 'itshashed', 'user', 'Pecsora Eszter');
insert into user (id, username, hashedPass, role, name) values (12, 'username12', 'itshashed', 'user', 'Benedek Zita');
insert into user (id, username, hashedPass, role, name) values (13, 'username13', 'itshashed', 'user', 'Fekete Botond');
insert into user (id, username, hashedPass, role, name) values (14, 'username14', 'itshashed', 'user', 'Ducsai Viktor');
insert into user (id, username, hashedPass, role, name) values (15, 'username15', 'itshashed', 'user', 'Szimku Aurél');

insert into USER_ADDRESS values (1, 1);
insert into USER_ADDRESS values (2, 2);
insert into USER_ADDRESS values (3, 3);
insert into USER_ADDRESS values (4, 4);
insert into USER_ADDRESS values (5, 5);
insert into USER_ADDRESS values (6, 6);
insert into USER_ADDRESS values (7, 7);
insert into USER_ADDRESS values (8, 1);
insert into USER_ADDRESS values (9, 2);
insert into USER_ADDRESS values (10, 3);
insert into USER_ADDRESS values (11, 4);
insert into USER_ADDRESS values (12, 5);
insert into USER_ADDRESS values (13, 6);
insert into USER_ADDRESS values (14, 7);
insert into USER_ADDRESS values (15, 1);
insert into USER_ADDRESS values (1, 2);
insert into USER_ADDRESS values (2, 3);
insert into USER_ADDRESS values (3, 4);
insert into USER_ADDRESS values (4, 5);
insert into USER_ADDRESS values (5, 6);
insert into USER_ADDRESS values (6, 7);